spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/test_db}
    username: ${SPRING_DATASOURCE_USERNAME:test_user}
    password: ${SPRING_DATASOURCE_PASSWORD:test_pass}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    cache: false

server:
  port: ${SERVER_PORT:8080}
